import Head from "next/head";
//всё что находиться внутри signedOut будет видно только НЕ залогиненым юзерам
//всё что находиться внутри signedIn будет видно только вошедшим юзерам
//SignInButton - перекидывает юзера на страничку логина (страница логина создаётся автоматически сайтом clerk)
//UserButton - перекидывает юзера в автоматически созданное меню настроек аккаунта
import { SignedOut, SignedIn, SignInButton, UserButton } from "@clerk/nextjs";
import { api, type RouterOutputs } from "../utils/api";
import Link from "next/link";

// Define the expected type for characters
type Character = RouterOutputs["profile"]["getUserCharacters"][number];

export default function Home() {
  const { data: characters, isLoading, isError } =
    api.profile.getUserCharacters.useQuery(undefined, {
      enabled: typeof window !== "undefined",
    });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <SignedOut> 
            <SignInButton />
          </SignedOut>

          <SignedIn>
            <UserButton />
            <div className="mt-4 text-white">
              <h2 className="text-2xl font-bold">Your Characters:</h2>
              {isLoading && <p>Loading characters...</p>}
              {isError && <p>Failed to load characters.</p>}
              {characters?.length ? (
                <ul>
                  {characters.map((character: Character) => (
                    <li key={character.id}>
                      <strong>{character.name}</strong>
                      <br />
                      Species: {character.species?.name ?? "Unknown"}
                      <br />
                      Background: {character.background?.name ?? "Unknown"}
                      <br />
                      Subclass: {character.subclass?.name ?? "None"}
                      <br />
                      Classes:{" "}
                      {character.characterClasses
                        ?.map((cc) => cc.class?.name ?? "Unknown")
                        .join(", ") ?? "None"}
                    </li>
                  ))}
                </ul>
              ) : (
                <p>No characters found.</p>
              )}
            </div>
          </SignedIn>
          <Link href="creation">Create a Character</Link>
        </div>
      </main>
    </>
  );
}
