import Head from "next/head";
import Link from "next/link";
import { SignedOut, SignedIn, SignInButton, UserButton } from "@clerk/nextjs";
import { api } from "../utils/api";

export default function Home() {
  const { data: characters, isLoading, isError } = api.profile.getUserCharacters.useQuery(
    undefined, // No input expected
    {
      enabled: typeof window !== "undefined", // Only run this query on client-side
    }
  );

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>

          <SignedOut>
            <SignInButton />
          </SignedOut>

          <SignedIn>
            <UserButton />
<div className="mt-4 text-white">
                <h2 className="text-2xl font-bold">Your Characters:</h2>
                {isLoading && <p>Loading characters...</p>}
                {isError && <p>Failed to load characters.</p>}
                {characters?.length ? (
                  <ul>
                    {characters.map((character: any) => (
                      <li key={character.id}>
                        <strong>{character.name}</strong><br />
                        Species: {character.species?.name || "Unknown"}<br />
                        Background: {character.background?.name || "Unknown"}<br />
                        Subclass: {character.subclass?.name || "None"}<br />
                        Classes: {character.characterClasses?.map((cc: any) => cc.class?.name).join(", ") || "None"}
                      </li>
                    ))}
                  </ul>
                ) : (
                  <p>No characters found.</p>
                )}
              </div>
          </SignedIn>
        </div>
      </main>
    </>
  );
}
